apiVersion: v1
entries:
  ambassador:
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-22T13:11:47.343588-05:00"
    description: A Helm chart for Kubernetes
    digest: 42c7aa386afcb7780c71e067b86da1a5cb83e1aa0222ed18c9895f6f8d57ee75
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-22T13:11:47.341897-05:00"
    description: A Helm chart for Kubernetes
    digest: bbbeea03857ddaf7cba8d9b1fb5e44942c48de0ab98311307cc7ac5c0f53ce83
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: 1.1.1
    created: "2021-01-22T13:11:47.341297-05:00"
    description: A Helm chart for Kubernetes
    digest: 0b9c00aa87a11e8b95837315512466ee29e21b139dbb908b1145cbcff948c666
    name: ambassador
    urls:
    - https://helxplatform.github.io/devops/charts/ambassador-0.1.1.tgz
    version: 0.1.1
  appstore:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.349138-05:00"
    description: A Helm chart for Kubernetes
    digest: 3d908cff9760f7f3a69d269e8af31fc4c633e93411d9304bf835d9fb1f6323a5
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.347945-05:00"
    description: A Helm chart for Kubernetes
    digest: 8d721efb24e10cd2b778c4ecb941a1d48ab45299cf527c0d23c9ec6c937c29f3
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.346729-05:00"
    description: A Helm chart for Kubernetes
    digest: 9a2bf6569bb2e7fdc0d5265e0c71f36c6bd2e0c697ca669cf0de205312026d3b
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.345463-05:00"
    description: A Helm chart for Kubernetes
    digest: abb5e5573cb3621565470f32142905b263721e12e288137b03614dc99c01ab43
    name: appstore
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/appstore-0.1.5.tgz
    version: 0.1.5
  backup-pvc-cronjob:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-01-22T13:11:47.349671-05:00"
    description: A Helm chart for Kubernetes
    digest: a3e4f2a4432c71b024f0d224e23323e76d0f55d76a5bf38fffcc5a213deeeaca
    name: backup-pvc-cronjob
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/backup-pvc-cronjob-0.1.0.tgz
    version: 0.1.0
  dug:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.360081-05:00"
    description: Helm chart for dug
    digest: b57582f508302d36081fa7baff36fe90d7f9a8d81a5664854b6a4587e9b8953d
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.358498-05:00"
    description: Helm chart for dug
    digest: f732fcca007daefe38081516b09c400693197312b9a7e8f9bca81c898964dcec
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.356332-05:00"
    description: Helm chart for dug
    digest: 9c7847838f5871917a7330b620c7f5bf7f9b2092c625ad6485d3688e8e7dbddf
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.355118-05:00"
    description: Helm chart for dug
    digest: b745a01f3dd1b7c7c489bd4563ac0f8cb553f6ab554216d3780786dd3ab5bbce
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.353772-05:00"
    description: Helm chart for dug
    digest: 7634b696743e704d4400a70ab2e405bd6ee87329ced02833b674f245272df770
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.350753-05:00"
    description: Helm chart for dug
    digest: ee2d1d87f78e9f4185a4f8813ae61d470b1986687a9f3b4e46f7c3e45e26f3a6
    name: dug
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/dug-0.2.2.tgz
    version: 0.2.2
  helx:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.373158-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: ca1aea2b70c1e82aa127474bb3e4b948977defba196f70d4bbd94e50c81e6175
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.16.tgz
    version: 0.2.16
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.369562-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: f0c3463a04aa8e39bc497f688058b97bf5bab435c37151077b5ca10bebbb560b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.15.tgz
    version: 0.2.15
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.363782-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 8559f9fb13687cd318b7b731c548c3c42609bdae2f3d6b762c96196602aa5d80
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.13.tgz
    version: 0.2.13
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.392158-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 88cd59a18a77e8cc73ba03c3811cbef741c39cd2777dd4b04efaaab66b7a2861
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.386919-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 564d847042553619fc1f9ce27999da37981575991101c0fe9c896e99913c7ec5
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.381947-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: 34eb97f6f34e44cc78c59dc648823519530c38413d684d4637fb9a03b2d7754b
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.376739-05:00"
    dependencies:
    - condition: ambassador.enabled
      name: ambassador
      repository: ""
    - condition: appstore.enabled
      name: appstore
      repository: ""
    - condition: backup-pvc-cronjob.enabled
      name: backup-pvc-cronjob
      repository: ""
    - condition: commonsshare.enabled
      name: commonsshare
      repository: ""
    - condition: dug.enabled
      name: dug
      repository: ""
    - condition: nfs-server.enabled
      name: nfs-server
      repository: ""
    - condition: nfsrods.enabled
      name: nfsrods
      repository: ""
    - condition: nginx.enabled
      name: nginx
      repository: ""
    - condition: tycho-api.enabled
      name: tycho-api
      repository: ""
    description: A Helm chart for Kubernetes
    digest: bbb4a31b706eb80035554ccbec5785881035afc620f67a238914d2405880e4bc
    name: helx
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/helx-0.2.6.tgz
    version: 0.2.6
  nfs-server:
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-22T13:11:47.393662-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: c74fee541cb7750b2e7a927e044310711979ff43a08510e51004efd4e23973bb
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: "0.8"
    created: "2021-01-22T13:11:47.392795-05:00"
    description: Creates an NFS server that can be used for PVCs.
    digest: 3da240f5b70d1daa0e35a8045f32055a86fff2a78ce1ec1c6297f58a6cf109ac
    name: nfs-server
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfs-server-0.2.0.tgz
    version: 0.2.0
  nfsrods:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.394595-05:00"
    description: A Helm chart for Kubernetes
    digest: aafd68ffcfa53d50f07e250e8247540e025fcab1b0c6a23bd08166bb85c867f9
    name: nfsrods
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/nfsrods-0.1.2.tgz
    version: 0.1.2
  nginx:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.39679-05:00"
    description: A Helm chart for Kubernetes
    digest: 2f34793848d6906a157f363f207e06f2a732da2762f263e04f9d50bdf7bf0343
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.39585-05:00"
    description: A Helm chart for Kubernetes
    digest: 54a8a4ca07bb8b30e9af033faf6f90cec00b62a28565bdbd625e82d01e883a60
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-22T13:11:47.395216-05:00"
    description: A Helm chart for Kubernetes
    digest: 9c5f4e86818bc1bd3630131b049c45a487848cd56b5da86f6780ef7b5f7083fe
    name: nginx
    urls:
    - https://helxplatform.github.io/devops/charts/nginx-0.1.5.tgz
    version: 0.1.5
  tycho-api:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.399522-05:00"
    description: A Helm chart for Kubernetes
    digest: d7ee15b095a274493b4192271ad91f50abee43aa67f1dcee041e170aa372a095
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.398615-05:00"
    description: A Helm chart for Kubernetes
    digest: c1ffd3174b21af041a3a5438bdd72ac6c7b9250887177a0385e7752e578a3d8b
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.398084-05:00"
    description: A Helm chart for Kubernetes
    digest: 98eca65de0a5d42f6f6ddc6557b0f3ef06aeca8b601d5d7f0b43f5740554d4d8
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2021-01-22T13:11:47.397347-05:00"
    description: A Helm chart for Kubernetes
    digest: aa4d2366914d00c03f7aca9002ab9506a7fd3f8d9993d2cfcd950dc1967c5528
    name: tycho-api
    type: application
    urls:
    - https://helxplatform.github.io/devops/charts/tycho-api-0.1.5.tgz
    version: 0.1.5
generated: "2021-01-22T13:11:47.339342-05:00"
