apiVersion: v2
name: helx-monitoring
description: Monitoring tools to use alongside HeLx
type: application
version: 0.1.5
dependencies:
  - name: cost-analyzer
    condition: cost-analyzer.enabled
    repository: https://kubecost.github.io/cost-analyzer/
    version: 1.86.0
  - name: loki-stack
    condition: loki-stack.enabled
    repository: https://grafana.github.io/helm-charts
    version: 2.4.1
