# Parent chart for HeLx.

ambassador:
  enabled: true
appstore:
  enabled: true
backup-pvc-cronjob:
  enabled: false
commonsshare:
  enabled: false
dug:
  enabled: false
nfs-server:
  enabled: true
nfsrods:
  enabled: false
nginx:
  enabled: true
tycho-api:
  enabled: true

global:
  tycho_api_service_name: helx-tycho-api
