# Parent chart for HeLx.

ambassador:
  enabled: true
appstore:
  enabled: true
backup-pvc-cronjob:
  enabled: false
commonsshare:
  enabled: false
dug:
  enabled: false
nfs-server:
  enabled: true
nfsrods:
  enabled: false
nginx:
  enabled: true
tycho-api:
  enabled: false
pod-reaper:
  enabled: true

global:
  tycho_api_service_name: helx-tycho-api
  # ambassador_service_name: helx-ambassador
  dug_web_service_name: helx-dug-web
  dug_search_client_service_name: helx-dug-search-client
  restartr_api_service_name: helx-restartr-api-service
  stdnfsPvc: stdnfs
