# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/datawire/ambassador
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 1.1.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

adminservice:
  type: ClusterIP

prp:
   # PRP cluster deployment: <True or False>
   deployment: false

roleIngresses: true

securityContext:
  runAsUser: 8888
  # runAsGroup: 8888
  # fsGroup: 8888
