# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  IP:
  httpPort: 80
  httpTargetPort: 80
  httpsPort: 443
  httpsTargetPort: 443
  serverName: _
  resolver: coredns.kube-system.svc
  # resolver: kube-dns.kube-system.svc
  # nodePort: 31337

# Set the DEV_PHASE.dev True, if Appstore/Tycho running locally. Else, set it to False
DEV_PHASE:
  dev: False

# Uncomment these SSL lines and create secret to use TLS/SSL
# kubectl create secret tls nginx-tls-secret --key nginx.key --cert nginx.crt
# SSL:
#   nginxTLSSecret: nginx-tls-secret

# ingress:
#   host: example.com
#   # ToDo: Make this cleaner.
#   class: traefik
#   traefikRouterTls: ""

varStorage:
  existingClaim: false
  claimName:
  storageSize: 2Gi
  storageClass:

image: heliumdatastage/nginx:bdcat-nginx-amb-2

restartrApi: false
dugApi: false
