# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: heliumdatastage/nginx
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  IP:
  httpPort: 80
  httpTargetPort: 8080
  httpsPort: 443
  httpsTargetPort: 8443
  serverName: _
  # nodePort: 31337

# Set the DEV_PHASE.dev True, if Appstore/Tycho running locally. Else, set it to False
DEV_PHASE:
  dev: False

# Uncomment these SSL lines and create secret to use TLS/SSL
# kubectl create secret tls nginx-tls-secret --key nginx.key --cert nginx.crt
# SSL:
#   nginxTLSSecret: nginx-tls-secret

# ingress:
#   host: example.com
#   # ToDo: Make this cleaner.
#   class: traefik
#   traefikRouterTls: ""

varStorage:
  existingClaim: false
  claimName:
  storageSize: 2Gi
  storageClass:

restartrApi: false
dugApi: false

# For TACC, set this to true and specify the hostname
http_host: false
