apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: {{ template "tycho-api.name" . }}
    app: {{ template "tycho-api.name" . }}
  name: {{ template "tycho-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ template "tycho-api.name" . }}
      app: {{ template "tycho-api.name" . }}
  template:
    metadata:
      labels:
        service: {{ template "tycho-api.name" . }}
        app: {{ template "tycho-api.name" . }}
    spec:
      containers:
      - command:
        - /usr/local/bin/gunicorn
        - --workers=2
        - --name=tycho
        - --timeout=600
        - tycho.api:app
        image: {{ .Values.image }}
        env:
        - name: CREATE_HOME_DIRS
          {{- if .Values.createHomeDirs }}
          value: "True"
          {{- else }}
          value: "False"
          {{- end }}
        - name: STDNFS_PVC
          value: {{ .Values.stdnfsPvc }}
        imagePullPolicy: "Always"
        name: {{ template "tycho-api.name" . }}
        ports:
        - containerPort: 8099
          protocol: TCP
      restartPolicy: Always
