apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tranql.fullname" . }}
  labels:
    {{- include "tranql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "tranql.selectorLabels" . | nindent 6 }}
      service-type: web-server
  template:
    metadata:
      labels:
        {{- include "tranql.selectorLabels" . | nindent 8 }}
        service-type: web-server
    spec:
      volumes:
        - name: config-yaml
          configMap:
            name: {{ include "tranql.fullname" . }}-configmap
            defaultMode: 0777
        - name: logs
          emptyDir: {}
      containers:
      - name: {{ include "tranql.fullname" . }}-web-container
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        command:
          - "/usr/local/bin/gunicorn"
          - "--workers={{ .Values.gunicorn.workerCount }}"
          - "--bind=0.0.0.0:{{ .Values.port }}"
          - "--timeout={{ .Values.gunicorn.workerTimeout }}"
          - "--access-logfile=$(ACCESS_LOG)"
          - "--error-logfile=$(ERROR_LOG)"
          - "--log-level=debug"
          - "tranql.api:app"
        ports:
          - containerPort: {{ .Values.port }}
            name: http
        env:
          - name: APP_PORT
            value: {{ .Values.port | quote }}
          - name: ACCESS_LOG
            value: "/var/nfs/tranql-frontend_access_log"
          - name: ERROR_LOG
            value: "/var/nfs/tranql-frontend_error_log"
          - name: REDIS_PASSWORD
          {{- if and .Values.redis.enabled .Values.redis.usePassword }}
            {{- if .Values.redis.password }}
            value: {{ .Values.redis.password }}
            {{- else }}
            valueFrom:
              secretKeyRef:
                {{- if .Values.redis.existingSecret }}
                name: {{ .Values.redis.existingSecret }}
                key: {{ .Values.redis.existingSecretPasswordKey }}
                {{- else }}
                name: {{ include "tranql.redis.secretName" .}}
                key: {{ include "tranql.redis.secretPasswordKey" . }}
                {{- end }}
            {{- end }}
          {{- else if .Values.existingRedis.password }}
            value: {{ .Values.existingRedis.password }}
          {{- else if .Values.existingRedis.secret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingRedis.secret }}
                key: {{ .Values.existingRedis.secretPasswordKey }}
          {{- end }}
          {{- if .Values.extraEnv }}
          {{ toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}
        volumeMounts:
          - name: logs
            mountPath: /var/nfs
          - name: config-yaml
            subPath: conf.yml
            mountPath: /tranql/tranql/conf.yml
          - name: config-yaml
            subPath: schema.yml
            mountPath: /tranql/tranql/conf/schema.yaml
        imagePullPolicy: Always
      restartPolicy: Always
