airflow:
  enabled: true
  airflow:
    image:
      repository: helxplatform/roger
      tag: "0.3.dev0"
      pullPolicy: Always
    executor: KubernetesExecutor
    config:
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "TRUE"
      AIRFLOW__CORE__LOAD_EXAMPLES: "FALSE"
      AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION: "FALSE"
      # Provide http://<URL to nginx >/<web-prefix>
      AIRFLOW__WEBSERVER__BASE_URL: ""
    extraEnv:
    - name: ROGER_ELASTICSEARCH_HOST
      value: helx-elasticsearch-master
    - name: ROGER_ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helx-elastic-secret
          key: password
    - name: ROGER_ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: helx-elastic-secret
          key: username
    - name: ROGER_REDISGRAPH_HOST
      value: helx-redis-master
    - name: ROGER_REDISGRAPH_GRAPH
      value: test
    - name: ROGER_REDISGRAPH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helx-redis-secret
          key: password
    - name: ROGER_REDISGRAPH_PORT
      value: "6379"
    - name: ROGER_DATA_DIR
      value: "/opt/airflow/share/data"
    - name: ROGER_ELASTICSEARCH_NBOOST__HOST
      value: nboost $ TODO compute this
    - name: ROGER_INDEXING_TRANQL__ENDPOINT
      value: http://helx-tranql:8081/tranql/tranql/query?dynamic_id_resolution=true&asynchronous=false
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          # Same as airflow.configSecretsName
          name: airflow-config-secrets
          key: fernet-key

    extraVolumeMounts:
      - name: airflow-data
        mountPath: /opt/airflow/share/data
    extraVolumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: search-data

    configSecretsName: airflow-config-secrets

    # Resource config for all task runner pods.
    kubernetesPodTemplate:
      resources: {}
        # requests:
          # memory: 1Gi

  externalRedis:
    host: helx-redis-master
    passwordSecret: helx-redis-secret
    passwordSecretKey: password

  web:
    extraPipPackages:
      ## the following configs require Flask-AppBuilder 3.2.0 (or later)
      - "Flask-AppBuilder~=3.2.0"
    service:
      annotations:
        getambassador.io/config: |
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: airflow-ui-amb
          prefix: /airflow
          service: helx-web:8080
          ambassador_id: ambassador-helx
          rewrite: /airflow/

    webserverConfig:
      stringOverride: |-
        import os
        from flask_appbuilder.security.manager import AUTH_REMOTE_USER
        from airflow.configuration import conf
        from flask import g
        from flask import get_flashed_messages, request, redirect, flash
        from flask_appbuilder import expose
        from flask_appbuilder._compat import as_unicode
        from flask_appbuilder.security.views import AuthView
        from flask_login import login_user, logout_user

        from airflow.www.security import AirflowSecurityManager

        class CustomAuthRemoteUserView(AuthView):
          login_template = ""

          @expose("/login/")
          def login(self):
              if g.user is not None and g.user.is_authenticated:
                  return redirect(self.appbuilder.get_url_for_index)
              username = request.environ.get('HTTP_REMOTE_USER')
              if username:
                  # https://github.com/dpgaspar/Flask-AppBuilder/blob/55b0976e1450295d5a26a06d28c5b992fb0b561e/flask_appbuilder/security/manager.py#L1201
                  user = self.appbuilder.sm.auth_user_remote_user(username)
                  if user is None:
                      flash(as_unicode(self.invalid_login_message), "warning")
                  else:
                      login_user(user)
              else:
                  flash(as_unicode(self.invalid_login_message), "warning")

              # Flush "Access is Denied" flash messaage
              get_flashed_messages()
              return redirect(self.appbuilder.get_url_for_index)

          @expose("/logout/")
          def logout(self):
              logout_user()
              return redirect("/admin/logout/")

        class CustomAirflowSecurityManager(AirflowSecurityManager):
          authremoteuserview = CustomAuthRemoteUserView

        SECURITY_MANAGER_CLASS = CustomAirflowSecurityManager

        basedir = os.path.abspath(os.path.dirname(__file__))
        # The SQLAlchemy connection string.
        SQLALCHEMY_DATABASE_URI = conf.get('core', 'SQL_ALCHEMY_CONN')
        # Flask-WTF flag for CSRF
        WTF_CSRF_ENABLED = True
        AUTH_TYPE = AUTH_REMOTE_USER
        AUTH_USER_REGISTRATION = False  # Set to True to allow users who are not already in the DB
  ingress:
    web:
      path: /airflow

  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/helxplatform/roger.git"
      repoSubPath: "dags"
      branch: "master"
      revision: "HEAD"
      syncWait: 60

  logs:
    path: /opt/airflow/share/logs
    persistence:
      enabled: true
      storageClass: "" ## WARNING: your StorageClass MUST SUPPORT `ReadWriteMany`
      accessMode: ReadWriteMany
      size: 1Gi

  redis:
    enabled: false

  flower:
    enabled: false

  workers:
    enabled: false

search-api:
  enabled: true
  web:
    deployment:
      extraEnv:
        - name: ELASTIC_API_HOST
          value: helx-elasticsearch-master
        - name: ELASTIC_API_PORT
          value: "9200"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-elastic-secret
              key: password
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: helx-elastic-secret
              key: username
        - name: REDIS_HOST
          value: helx-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-redis-secret
              key: password
        - name: REDIS_PORT
          value: "6379"
        - name: NBOOST_API_HOST
          value: nboost $ TODO compute this
    service:
      annotations:
        getambassador.io/config: |
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: search-api
          prefix: /search
          service: helx-search-api-webserver:5551
          rewrite: /search
          ambassador_id: ambassador-helx
          cors:
            origins: "*"
            methods: POST, OPTIONS
            headers:
              - Content-Type
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: search-api-kg
          prefix: /search_kg
          service: helx-search-api-webserver:5551
          ambassador_id: ambassador-helx
          ambassador_id: ambassador-helx
          rewrite: /search_kg
          cors:
            origins: "*"
            methods: POST, OPTIONS
            headers:
              - Content-Type
  redis:
    enabled: false
  elasticsearch:
    enabled: false

search-ui:
  extraEnv:
    - name: PUBLIC_URL
      value: "/ui"
  service:
    annotations:
      getambassador.io/config: |
        ---
        apiVersion: ambassador/v1
        kind: Mapping
        name: search-ui
        prefix: /ui
        service: helx-search-ui:8080
        ambassador_id: ambassador-helx

elasticsearch:
  enabled: true
  imageTag: "7.12.0"
  clusterName: helx-elasticsearch

  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helx-elastic-secret
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: helx-elastic-secret
          key: username

nboost:
  enabled: false

persistence:
  storageClass: ""
  pvcSize: 1Gi

redis:
  enabled: true
#  dumpUri: "https://stars.renci.org/var/kgx_data/roger_graph.rdb"
#  configmap: |-
#    # Disables appendonly , this instance is readonly. And needs to be
#    # seeded from RDB files if needed.
#    appendonly no
#    # Disable RDB persistence, AOF persistence already enabled.
#    save ""
  persistence:
    existingClaim: "redis-data"
  usePassword: true
  clusterDomain: cluster.local
  existingSecret: helx-redis-secret
  existingSecretPasswordKey: password
  image:
    repository: redislabs/redisgraph
    tag: 2.2.14
  redis:
    command: "redis-server"
  cluster:
    slaveCount: 1
  master:
    resources:
      requests:
        memory: 8Gi
        cpu: 200m
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379
  slave:
    resources:
      requests:
        memory: 8Gi
        cpu: 200m
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379

secrets:
  elastic:
    name: helx-elastic-secret
    user: elastic
    userKey: username
    passwordKey: password
  redis:
    name: helx-redis-secret
    passwordKey: password

tranql:
  enabled: true
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: tranql-amb
      prefix: /tranql
      rewrite: /tranql
      service: helx-tranql:8081
      ambassador_id: ambassador-helx
      cors:
        origins: "*"
        methods: POST, OPTIONS
        headers:
          - Content-Type
      timeout_ms: 0
  existingRedis:
    host: helx-redis-slave
    port: 6379
    secret: helx-redis-secret
    secretPasswordKey: password
  extraEnv:
    - name: WEB_PATH_PREFIX
      value: "/tranql"

  redis:
    enabled: false
