apiVersion: v1
kind: Secret
metadata:
  name: cloud-top-env
data:
  USER_HOME: {{ .Values.apps.CLOUD_TOP_USER_HOME | b64enc }}
  USER_NAME: {{ .Values.apps.CLOUD_TOP_USER_NAME | b64enc }}
  VNC_PW: {{ .Values.apps.CLOUD_TOP_VNC_PW | b64enc | quote }}
