apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: {{ include "appstore.fullname" . }}-env
data:
  # /usr/src/inst-mgmt is default location if db is created in the container.
  # OAUTH_DB_DIR: /usr/src/inst-mgmt
  # /var/lib/sqlite3 is used for PVC mount point.
  DJANGO_SETTINGS_MODULE: appstore.settings.{{ .Values.djangoSettings }}_settings
  # Default is always "True" on the server. Change to "False" in prod.
  DEBUG: "True"
  OAUTH_DB_DIR: /var/lib/sqlite3
  OAUTH_DB_FILE: DATABASE.sqlite3
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: "{{ .Values.ACCOUNT_DEFAULT_HTTP_PROTOCOL }}"
  DEV_PHASE: prod
  # Just adding these ports temporarily until they have a default value in the code.
  BRAINI_PORT: "1247"
  NRC_PORT: "1247"
  ALLOW_DJANGO_LOGIN: "{{ .Values.django.ALLOW_DJANGO_LOGIN }}"
  ALLOW_SAML_LOGIN: "{{ .Values.django.ALLOW_SAML_LOGIN }}"
  WHITELIST_REDIRECT: "{{ .Values.django.WHITELIST_REDIRECT }}"
  SAML2_AUTH_ASSERTION_URL: "{{ .Values.django.saml2auth.ASSERTION_URL }}"
  SAML2_AUTH_ENTITY_ID: "{{ .Values.django.saml2auth.ENTITY_ID }}"
  IMAGE_DOWNLOAD_URL: "{{ .Values.django.IMAGE_DOWNLOAD_URL }}"
