apiVersion: v1
kind: Secret
metadata:
  name: csappstore-secret
data:
  APPSTORE_DJANGO_USERNAME: {{ .Values.django.APPSTORE_DJANGO_USERNAME | b64enc }}
  APPSTORE_DJANGO_PASSWORD: {{ .Values.django.APPSTORE_DJANGO_PASSWORD | b64enc }}
  APPSTORE_SECRET_KEY: {{ .Values.django.SECRET_KEY | b64enc }}
  EMAIL_HOST_USER: {{ .Values.django.EMAIL_HOST_USER | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.django.EMAIL_HOST_PASSWORD | b64enc }}
  OAUTH_PROVIDERS: {{ .Values.django.oauth.OAUTH_PROVIDERS | b64enc }}
  {{ if .Values.django.oauth.GITHUB_NAME }}
  GITHUB_NAME: {{ .Values.django.oauth.GITHUB_NAME | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.django.oauth.GITHUB_CLIENT_ID | b64enc }}
  GITHUB_SECRET: {{ .Values.django.oauth.GITHUB_SECRET | b64enc }}
    {{ if .Values.django.oauth.GITHUB_KEY }}
  GITHUB_KEY: {{ .Values.django.oauth.GITHUB_KEY | b64enc }}
    {{- end }}
    {{ if .Values.django.oauth.GITHUB_SITES }}
  GITHUB_SITES: {{ .Values.django.oauth.GITHUB_SITES | b64enc }}
    {{- end }}
  {{- end }}
  {{ if .Values.django.oauth.GOOGLE_NAME }}
  GOOGLE_NAME: {{ .Values.django.oauth.GOOGLE_NAME | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.django.oauth.GOOGLE_CLIENT_ID | b64enc }}
  GOOGLE_SECRET: {{ .Values.django.oauth.GOOGLE_SECRET | b64enc }}
    {{ if .Values.django.oauth.GOOGLE_KEY }}
  GOOGLE_KEY: {{ .Values.django.oauth.GOOGLE_KEY | b64enc }}
    {{- end }}
    {{ if .Values.django.oauth.GOOGLE_SITES }}
  GOOGLE_SITES: {{ .Values.django.oauth.GOOGLE_SITES | b64enc }}
    {{- end }}
  {{- end }}
  {{- if .Values.irods.enabled }}
  BRAINI_RODS: {{ .Values.irods.BRAINI_RODS | b64enc }}
  NRC_MICROSCOPY_IRODS: {{ .Values.irods.NRC_MICROSCOPY_IRODS | b64enc }}
  RODS_USERNAME: {{ .Values.irods.RODS_USERNAME | b64enc }}
  RODS_PASSWORD: {{ .Values.irods.RODS_PASSWORD | b64enc }}
  IROD_COLLECTIONS: {{ .Values.irods.IROD_COLLECTIONS | b64enc }}
  IROD_ZONE: {{ .Values.irods.IROD_ZONE | b64enc }}
  {{- end }}
