apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ template "appstore.name" . }}
  labels:
    app: cs-{{ template "appstore.name" . }}
spec:
  selector:
    matchLabels:
      app: cs-{{ template "appstore.name" . }}
  template:
    metadata:
      labels:
        app: cs-{{ template "appstore.name" . }}
    spec:
      initContainers:
      {{- if .Values.postgres }}
      - name: {{ .Values.db.name }}-init
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{ .Values.db.name }}; do echo waiting for postgres; sleep 2; done;']
      {{- end }}
      containers:
      - name: cs-{{ .Values.db.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command: ['/bin/bash', '-c']
        args: ["bin/appstore updatedb {{ .Values.djangoSettings }} && bin/appstore createsuperuser && bin/appstore run {{ .Values.djangoSettings }}"]
        # For debugging when things go wrong.
        # args: ["-c", "while true; do date; sleep 5; done"]
        env:
        # - name: DATABASE_USER
        #   valueFrom:
        #     secretKeyRef:
        #       key: DATABASE_USER
        #       name: csappstore-secret
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: DATABASE_PASSWORD
        #       name: csappstore-secret
        - name: OAUTH_DB_DIR
          valueFrom:
            configMapKeyRef:
              key: OAUTH_DB_DIR
              name: csappstore-env
        - name: OAUTH_DB_FILE
          valueFrom:
            configMapKeyRef:
              key: OAUTH_DB_FILE
              name: csappstore-env
        - name: ACCOUNT_DEFAULT_HTTP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: ACCOUNT_DEFAULT_HTTP_PROTOCOL
              name: csappstore-env
        - name: TYCHO_URL
          valueFrom:
            configMapKeyRef:
              key: TYCHO_URL
              name: csappstore-env
        - name: DEV_PHASE
          valueFrom:
            configMapKeyRef:
              key: DEV_PHASE
              name: csappstore-env
        - name: BRAINI_PORT
          valueFrom:
            configMapKeyRef:
              key: BRAINI_PORT
              name: csappstore-env
        - name: NRC_PORT
          valueFrom:
            configMapKeyRef:
              key: NRC_PORT
              name: csappstore-env
        - name: CSAPPSTORE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: csappstore-secret
        - name: APPSTORE_DJANGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: APPSTORE_DJANGO_USERNAME
              name: csappstore-secret
        - name: APPSTORE_DJANGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: APPSTORE_DJANGO_PASSWORD
              name: csappstore-secret
        - name: OAUTH_PROVIDERS
          valueFrom:
            secretKeyRef:
              key: OAUTH_PROVIDERS
              name: csappstore-secret
        - name: GITHUB_NAME
          valueFrom:
            secretKeyRef:
              key: GITHUB_NAME
              name: csappstore-secret
        - name: GITHUB_SITES
          valueFrom:
            secretKeyRef:
              key: GITHUB_SITES
              name: csappstore-secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_ID
              name: csappstore-secret
        - name: GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_SECRET
              name: csappstore-secret
        - name: GOOGLE_NAME
          valueFrom:
            secretKeyRef:
              key: GOOGLE_NAME
              name: csappstore-secret
        - name: GOOGLE_SITES
          valueFrom:
            secretKeyRef:
              key: GOOGLE_SITES
              name: csappstore-secret
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GOOGLE_CLIENT_ID
              name: csappstore-secret
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              key: GOOGLE_SECRET
              name: csappstore-secret
        - name: BRAINI_RODS
          valueFrom:
            secretKeyRef:
              key: BRAINI_RODS
              name: csappstore-secret
        - name: NRC_MICROSCOPY_IRODS
          valueFrom:
            secretKeyRef:
              key: NRC_MICROSCOPY_IRODS
              name: csappstore-secret
        - name: RODS_USERNAME
          valueFrom:
            secretKeyRef:
              key: RODS_USERNAME
              name: csappstore-secret
        - name: RODS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RODS_PASSWORD
              name: csappstore-secret
        - name: IROD_COLLECTIONS
          valueFrom:
            secretKeyRef:
              key: IROD_COLLECTIONS
              name: csappstore-secret
        - name: IROD_ZONE
          valueFrom:
            secretKeyRef:
              key: IROD_ZONE
              name: csappstore-secret
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: EMAIL_HOST_USER
              name: csappstore-secret
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: EMAIL_HOST_PASSWORD
              name: csappstore-secret
        ports:
        - containerPort: 8000
      {{- if .Values.oauth.pvcname }}
        volumeMounts:
          - mountPath: /var/lib/sqlite3
            name: appstore-oauth-volume
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.oauth.pvcname }}
      volumes:
        - name: appstore-oauth-volume
          persistentVolumeClaim:
            claimName: {{ .Values.oauth.pvcname }}
      {{- end }}
