apiVersion: v1
kind: Secret
metadata:
  name: dicom-cloudtop-env
data:
  USER_HOME: {{ .Values.apps.DICOMCT_USER_HOME }}
  USER_NAME: {{ .Values.apps.DICOMCT_USER_NAME }}
  VNC_PW: {{ .Values.apps.DICOMCT_VNC_PW }}
