apiVersion: v1
kind: Secret
metadata:
  name: dicom-gh-env
data:
  USER_HOME: {{ .Values.apps.DICOMGH_USER_HOME | b64enc }}
  USER_NAME: {{ .Values.apps.DICOMGH_USER_NAME | b64enc }}
  VNC_PW: {{ .Values.apps.DICOMGH_VNC_PW | b64enc | quote }}
  {{- if .Values.apps.DICOMGH_GOOGLE_CLIENT_ID }}
  CLIENT_ID: {{ .Values.apps.DICOMGH_GOOGLE_CLIENT_ID | b64enc }}
  {{- end }}
