{{- if .Values.postgres }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: {{ .Values.db.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: csappstore-env
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: appstore-db-volume
      volumes:
        - name: appstore-db-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
{{- end }}
