apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appstore.fullname" . }}
data:
  {{ if .Values.django.AUTHORIZED_USERS }}
  AUTHORIZED_USERS: {{ .Values.django.AUTHORIZED_USERS | b64enc }}
  {{- end }}
  {{ if .Values.django.REMOVE_AUTHORIZED_USERS }}
  REMOVE_AUTHORIZED_USERS: {{ .Values.django.REMOVE_AUTHORIZED_USERS | b64enc }}
  {{- end }}
  {{ if .Values.django.DOCKSTORE_APPS_BRANCH }}
  DOCKSTORE_APPS_BRANCH: {{ .Values.django.DOCKSTORE_APPS_BRANCH | b64enc}}
  {{- end }}
  APPSTORE_DJANGO_USERNAME: {{ .Values.django.APPSTORE_DJANGO_USERNAME | b64enc | quote }}
  {{ if .Values.django.APPSTORE_DJANGO_PASSWORD }}
  APPSTORE_DJANGO_PASSWORD: {{ .Values.django.APPSTORE_DJANGO_PASSWORD | b64enc }}
  {{- else }}
  {{- if .Release.IsInstall }}
  APPSTORE_DJANGO_PASSWORD: {{ randAlphaNum 20 | b64enc | quote }}
  {{ else }}
  APPSTORE_DJANGO_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace ( include "appstore.fullname" . )).data "APPSTORE_DJANGO_PASSWORD" }}
  {{ end }}
  {{- end }}
  APPSTORE_SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
  {{ if .Values.django.EMAIL_HOST_USER }}
  EMAIL_HOST_USER: {{ .Values.django.EMAIL_HOST_USER | b64enc }}
  {{- else }}
  EMAIL_HOST_USER: ""
  {{- end }}
  {{ if .Values.django.EMAIL_HOST_PASSWORD }}
  EMAIL_HOST_PASSWORD: {{ .Values.django.EMAIL_HOST_PASSWORD | b64enc }}
  {{- else }}
  EMAIL_HOST_PASSWORD: ""
  {{- end }}
  {{ if .Values.django.WHITELIST_REDIRECT }}
  WHITELIST_REDIRECT: {{ .Values.django.WHITELIST_REDIRECT | b64enc }}
  {{- else }}
  WHITELIST_REDIRECT: ""
  {{- end }}
  {{ if .Values.django.oauth.OAUTH_PROVIDERS }}
  OAUTH_PROVIDERS: {{ .Values.django.oauth.OAUTH_PROVIDERS | b64enc }}
  {{- else }}
  OAUTH_PROVIDERS: ""
  {{- end }}
  {{ if .Values.django.oauth.GITHUB_NAME }}
  GITHUB_NAME: {{ .Values.django.oauth.GITHUB_NAME | b64enc }}
  GITHUB_CLIENT_ID: {{ .Values.django.oauth.GITHUB_CLIENT_ID | b64enc }}
  GITHUB_SECRET: {{ .Values.django.oauth.GITHUB_SECRET | b64enc }}
  GITHUB_KEY: {{ .Values.django.oauth.GITHUB_KEY | b64enc | quote }}
  GITHUB_SITES: {{ .Values.django.oauth.GITHUB_SITES | b64enc | quote }}
  {{- end }}
  {{ if .Values.django.oauth.GOOGLE_NAME }}
  GOOGLE_NAME: {{ .Values.django.oauth.GOOGLE_NAME | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.django.oauth.GOOGLE_CLIENT_ID | b64enc }}
  GOOGLE_SECRET: {{ .Values.django.oauth.GOOGLE_SECRET | b64enc }}
  GOOGLE_KEY: {{ .Values.django.oauth.GOOGLE_KEY | b64enc | quote }}
  GOOGLE_SITES: {{ .Values.django.oauth.GOOGLE_SITES | b64enc | quote }}
  {{- end }}
  {{- if .Values.irods.enabled }}
  BRAINI_RODS: {{ .Values.irods.BRAINI_RODS | b64enc }}
  NRC_MICROSCOPY_IRODS: {{ .Values.irods.NRC_MICROSCOPY_IRODS | b64enc }}
  RODS_USERNAME: {{ .Values.irods.RODS_USERNAME | b64enc }}
  RODS_PASSWORD: {{ .Values.irods.RODS_PASSWORD | b64enc }}
  IROD_COLLECTIONS: {{ .Values.irods.IROD_COLLECTIONS | b64enc }}
  IROD_ZONE: {{ .Values.irods.IROD_ZONE | b64enc }}
  {{- end }}
  {{- if .Values.ambassador.id }}
  AMBASSADOR_ID: {{ .Values.ambassador.id | b64enc }}
  {{- end }}
