image: renciorg/tranql-app
imageTag: 0.38
replicas: 1
port: 8081
gunicorn:
  workerCount: 4
  workerTimeout: 300
service:
  type: ClusterIP
extraEnv: []
annotations: {}

secrets:
  redis:
    name: helx-redis-secret
    passwordKey: password