redis:
  image:
    repository: redislabs/redisgraph
    tag: 2.2.14
  redis:
    command: "redis-server"
  clusterDomain: "blackbalsam-cluster"
  cluster:
    slaveCount: 1
  usePassword: true
  master:
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
  slave:
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
  existingSecret: roger-redis-secret
  existingSecretPasswordKey: redis-password

elasticSearch:
  host: dug-elasticsearch
  port: 9200


airflow:
  # size of roger-data-pvc for storing files used by pipelines
  pvcSize: 5Gi
  #
  # NOTE:
  # - This is intended to be a `custom-values.yaml` starting point for non-production deployment (like minikube)

  # External Dependencies:
  # - A PUBLIC git repo for DAGs: ssh://git@repo.example.com:my-airflow-dags.git
  #

  ###################################
  # Airflow - Common Configs
  ###################################
  airflow:
    ## the airflow executor type to use
    ##
    image:
      repository: helxplatform/airflow
      tag: "develop-v0.0.3"
    #  executor: CeleryExecutor
    executor: KubernetesExecutor

    ## environment variables for the web/scheduler/worker Pods (for airflow configs)
    ##
    config:
      # Security
      AIRFLOW__CORE__SECURE_MODE: "True"
      AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__WEBSERVER__EXPOSE_HOSTNAME: "False"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      AIRFLOW__KUBERNETES__GIT_REPO: "https://git@github.com/helxplatform/roger.git"
      # https://airflow.apache.org/docs/apache-airflow/1.10.12/configurations-ref.html#git-ssh-key-secret-name
#      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-secrets"
      # @TODO change this to master.
      AIRFLOW__KUBERNETES__GIT_BRANCH: "develop"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
      AIRFLOW__KUBERNETES__GIT_SYNC_DEST: "roger"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "roger"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "TRUE"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "helxplatform/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "develop-v0.0.3"
      # DAGS
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      ## Disable noisy "Handling signal: ttou" Gunicorn log messages
      GUNICORN_CMD_ARGS: "--log-level WARNING"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080/airflow"
      AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: "airflow-env-config"

    ###################################
    # Volumes
    ###################################
    extraVolumeMounts:
      - name: roger-data
        mountPath: /dags/roger/data

    ## extra volumes for the web/scheduler/worker Pods

    extraVolumes:
      - name: roger-data
        emptyDir: {}

    configSecretsName: airflow-config-secrets

    # https://github.com/airflow-helm/charts/tree/main/charts/airflow#docs-airflow---configmaps
    extraConfigmapMounts:
      - name: airlflow-webserver-config
        mountPath: /opt/airflow/webserver_config.py
        configMap: airflow-webserver-config
        readOnly: true
        subPath: webserver_config.py

    extraEnv:
      - name: ADMIN_REMOTE_USER_NAME
        value: admin
      - name: AIRFLOW__CORE__FERNET_KEY
        valueFrom:
          secretKeyRef:
            # Same as airflow.configSecretsName
            name: airflow-config-secrets
            key: fernet-key

      # This are going to be used to compute env for worker pods.
      - name: ELASTIC_SEARCH_PASSWORD_SECRET
        value: dug-secrets
      - name: ELASTIC_SEARCH_PASSWORD_SECRET_KEY
        value: ELASTIC_PASSWORD
      - name: REDIS_PASSWORD_SECRET
        # Same as redis.existingSecret
        value: roger-redis-secret
      - name: REDIS_PASSWORD_SECRET_KEY
        # same as redis.existingSecretKey
        value: redis-password

  ###################################
  # Airflow - WebUI Configs
  ###################################

  web:
    ## configs for the Service of the web Pods
    ##
    service:
      type: ClusterIP


  ###################################
  # Airflow - Worker Configs
  ###################################
  workers:
    ## the number of workers Pods to run
    ##
    ### Kubernetes executor doesn't need worker
    replicas: 0

  ###################################
  # Airflow - DAGs Configs
  ###################################
  dags:
    ## configs for the DAG git repository & sync container
    ##
    git:
      ## url of the git repository
      url: "https://git@github.com/helxplatform/roger.git"

      ## the branch/tag/sha1 which we clone
      ##
      ref: develop


      ## the host name of the git repo
      ##
      ## NOTE:
      ## - this is ONLY REQUIRED for SSH git repos
      ##
      ## EXAMPLE:
      ##   repoHost: "github.com"
      ##
      repoHost: "github.com"

      ## the port of the git repo
      ## NOTE:
      ## - this is ONLY REQUIRED for SSH git repos
      ##

      ## configs for the git-sync container
      gitSync:
        ## enable the git-sync sidecar container
        enabled: true
        ## the git sync interval in seconds
        refreshTime: 60
    installRequirments: true

  ###################################
  # Database - PostgreSQL Chart
  ###################################
  postgresql:
    enabled: true

  ###################################
  # Database - Redis Chart
  ###################################
  redis:
    enabled: false

  # airflow.airflow.config.AIRFLOW__WEBSERVER__BASE_URL path suffix
  ingress:
    web:
      # This should be equivalent to
      path: /airflow



tranql:
  image: renciorg/tranql-app
  imageTag: develop-test
  replicas: 1
  port: 8081
  gunicorn:
    workerCount: 4
    workerTimeout: 300
  service:
    type: ClusterIP


web:
  ambassador:
    tranql:
      prefix: /tranql
      map_name: tranql-amb
    airflowUI:
      prefix: /airflow
      rewrite: /airflow/
      map_name: airflow-ui-amb
