apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.elasticsearch.app_name }}
  name: {{ .Values.elasticsearch.statefulset_name }}
spec:
  serviceName: {{ .Values.elasticsearch.service_name }}
  replicas: {{ .Values.elasticsearch.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.app_name }}
    spec:
      initContainers:
        - name: sysctl
          image: bitnami/minideb:buster
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          command:
            - /scripts/sysctl.sh
          securityContext:
            privileged: true
          volumeMounts:
            - name: elasticsearch-initcontainer-volume
              mountPath: /scripts/sysctl.sh
              subPath: sysctl.sh
      volumes:
        - name: elasticsearch-initcontainer-volume
          configMap:
            name: {{ .Values.elasticsearch.init_config_name }}
            defaultMode: 0755
        - name: elasticsearch-certs
          secret:
            secretName: {{ .Values.elasticsearch.certs_secret }}
      securityContext:
        fsGroup: 1001
      containers:
      - image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        name: {{ .Values.elasticsearch.app_name }}-container
        ports:
          - containerPort: {{ .Values.elasticsearch.rest_port }}
          - containerPort: {{ .Values.elasticsearch.nodes_com_port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.elasticsearch.nodes_com_port }}
          initialDelaySeconds: {{ .Values.elasticsearch.liveness.initial_delay }}
          periodSeconds: {{ .Values.elasticsearch.liveness.check_interval }}
        volumeMounts:
        - name: {{ .Values.elasticsearch.app_name }}-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-certs
          readOnly: true
          mountPath: /usr/share/elasticsearch/config/certificates
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: ELASTIC_PASSWORD
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.elasticsearch.xms }} -Xmx{{ .Values.elasticsearch.xmx }}"
        - name: xpack.security.enabled
          value: 'true'
        - name: xpack.security.transport.ssl.enabled
          value: 'true'
        - name: xpack.security.transport.ssl.verification_mode
          value: 'certificate'
        - name: xpack.security.transport.ssl.keystore.path
          value: /usr/share/elasticsearch/config/certificates/elastic-certificates.p12
        - name: xpack.security.transport.ssl.truststore.path
          value: /usr/share/elasticsearch/config/certificates/elastic-certificates.p12
        - name: cluster.name
          value: {{ .Values.elasticsearch.cluster_name }}
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.initial_master_nodes
          value: {{ .Values.elasticsearch.initial_master_name }}
        - name: discovery.seed_hosts
          value: {{ .Values.elasticsearch.service_name }}
        - name: network.host
          value: "0.0.0.0"
        {{- range $role, $enabled := .Values.elasticsearch.roles }}
        - name: node.{{ $role }}
          value: "{{ $enabled }}"
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.elasticsearch.app_name }}-data
      labels:
        app: {{ .Values.elasticsearch.app_name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.elasticsearch.storage_class }}
        storageClassName: {{ .Values.elasticsearch.storage_class }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.elasticsearch.storage_size }}
