{{ if .Values.create_pvcs }}
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: {{ .Values.neo4j.app_name }}
    name: {{ .Values.neo4j.pvc_name }}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.neo4j.storage_size }}
    {{- if .Values.neo4j.storage_class }}
    storageClassName: {{ .Values.neo4j.storage_class }}
    {{- end }}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: {{ .Values.redis.app_name }}
    name: {{ .Values.redis.pvc_name }}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.redis.storage_size }}
    {{- if .Values.redis.storage_class }}
    storageClassName: {{ .Values.redis.storage_class }}
    {{- end }}
kind: List
{{ end }}
