apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "ambassador.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ambassador.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "ambassador.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
