apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "ambassador.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: [ "services" ]
  verbs: ["get", "list", "watch"]
